# Generated by Django 3.2 on 2021-07-31 00:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80, verbose_name='Prénoms')),
                ('lastname', models.CharField(max_length=80, verbose_name='NOM')),
                ('roomid', models.PositiveIntegerField(default=0, verbose_name='N° de Chambre')),
                ('startdate', models.DateField(default=django.utils.timezone.localdate, verbose_name="Date D'entrée")),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='location_manager.building', verbose_name='Maison')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='location_manager.owner'),
        ),
    ]
