# Generated by Django 3.2 on 2021-07-31 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_manager', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='location_manager.customer'),
        ),
    ]
