# Generated by Django 3.2 on 2021-07-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_manager', '0005_alter_customer_roomid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='building',
            table='Maison',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Locataire',
        ),
        migrations.AlterModelTable(
            name='owner',
            table='Client',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='Paiement',
        ),
    ]
