# Generated by Django 3.2 on 2021-07-31 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_manager', '0006_auto_20210731_1029'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='building',
            table='maison',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='locataire',
        ),
        migrations.AlterModelTable(
            name='owner',
            table='client',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='paiement',
        ),
    ]
