# Generated by Django 3.2 on 2021-07-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_manager', '0007_auto_20210731_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Locataire',
        ),
        migrations.RenameModel(
            old_name='Building',
            new_name='Maison',
        ),
        migrations.RenameModel(
            old_name='Payment',
            new_name='Paiement',
        ),
    ]
